FEAT: updatnuta deploy akce

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,43 +10,44 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repo
-        uses: actions/checkout@v4
-
-      - name: Build docker image
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          tags: test:latest
-          load: true
-
       - name: Deploy to server
+        shell: bash
         run: |
-          echo "Volání deploy endpointu..."
+          set -o pipefail
+          echo "▶️ Volá se deploy endpoint…"
 
-          # volani api
-          curl -s -w "\n%{http_code}" -o response.json \
-            -X POST "https://deploy.emsio.cz/ghad/df/v1/run" \
+          # post request na deploy endpoint
+          curl --no-buffer -X POST \
             -H "X-GHAD-Token: ${{ secrets.DEPLOY_TOKEN }}" \
             -H "X-GHRP-Uuid: ${{ secrets.PROJECT_UUID }}" \
-            -H "X-GHRP-Name: ${{ github.repository }}" > result.txt
+            -H "X-GHRP-Name: ${{ github.repository }}" \
+            https://deploy.emsio.cz/ghad/df/v1/run \
+            -w "\n%{http_code}" \
+          | tee full_response.txt
 
-          http_code=$(tail -n1 result.txt)
-          body=$(head -n -1 result.txt)
+      - name: Publish step summary
+        shell: bash
+        run: |
+          # parse HTTP status and body
+          http_code=$(tail -n1 full_response.txt | grep -Eo '[0-9]{3}$')
+          
+          # nastaveni body podle vysledku
+          if [ "$http_code" -ne 200 ]; then
+            body="❌ Chyba: Server vrátil $http_code"
+          else
+            body="Úspěšně nasazeno na server"
+          fi
 
-          echo "Server odpověď: $body"
-          echo "Status code: $http_code"
-
-          # vypis do step summary
+          # summary
           echo "### 🚀 Deploy výstup" >> $GITHUB_STEP_SUMMARY
           echo "" >> $GITHUB_STEP_SUMMARY
           echo "**HTTP status:** \`$http_code\`" >> $GITHUB_STEP_SUMMARY
           echo "" >> $GITHUB_STEP_SUMMARY
-          echo '```json' >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
           echo "$body" >> $GITHUB_STEP_SUMMARY
           echo '```' >> $GITHUB_STEP_SUMMARY
 
-          # pokud status neni 200, ukoncit jako error
+          # fail jobu pokud je errro
           if [ "$http_code" -ne 200 ]; then
             echo "❌ Chyba: server vrátil $http_code"
             exit 1
